# -*-Makefile-*-

include   $(KERN_DIR)/trap/TSyscallArg/Makefile.inc
include   $(KERN_DIR)/trap/TSyscall/Makefile.inc
include   $(KERN_DIR)/trap/TDispatch/Makefile.inc
include   $(KERN_DIR)/trap/TTrapHandler/Makefile.inc
