# -*-Makefile-*-

include   $(KERN_DIR)/pmm/MATIntro/Makefile.inc
include   $(KERN_DIR)/pmm/MATInit/Makefile.inc
include   $(KERN_DIR)/pmm/MATOp/Makefile.inc
include   $(KERN_DIR)/pmm/MContainer/Makefile.inc
