# -*-Makefile-*-

include   $(KERN_DIR)/thread/PKCtxIntro/Makefile.inc
include   $(KERN_DIR)/thread/PKCtxNew/Makefile.inc
include   $(KERN_DIR)/thread/PTCBIntro/Makefile.inc
include   $(KERN_DIR)/thread/PTCBInit/Makefile.inc
include   $(KERN_DIR)/thread/PTQueueIntro/Makefile.inc
include   $(KERN_DIR)/thread/PTQueueInit/Makefile.inc
include   $(KERN_DIR)/thread/PCurID/Makefile.inc
include   $(KERN_DIR)/thread/PThread/Makefile.inc
