# -*-Makefile-*-

include   $(KERN_DIR)/vmm/MPTIntro/Makefile.inc
include   $(KERN_DIR)/vmm/MPTOp/Makefile.inc
include   $(KERN_DIR)/vmm/MPTComm/Makefile.inc
include   $(KERN_DIR)/vmm/MPTKern/Makefile.inc
include   $(KERN_DIR)/vmm/MPTInit/Makefile.inc
include   $(KERN_DIR)/vmm/MPTNew/Makefile.inc
